name: "sast-scan"

on:
  push:
    branches: [githubcicd]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Add timeout to prevent hanging jobs

    strategy:
      matrix:
        node-version: [16.x]
      fail-fast: false  # Continue with other jobs if one fails

    steps:
      - uses: actions/checkout@v3  # Updated to v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'  # Enable npm caching

      - name: Install Dependencies
        run: |
          npm ci --force
        continue-on-error: true  # Continue even if npm install has warnings

      - name: Cache OWASP Dependency Check
        id: cache-dc
        uses: actions/cache@v3
        with:
          path: dependency-check
          key: dc-7.2.0

      - name: Download OWASP Dependency Check
        if: steps.cache-dc.outputs.cache-hit != 'true'
        run: |
          wget -q https://github.com/jeremylong/DependencyCheck/releases/download/v7.2.0/dependency-check-7.2.0-release.zip
          unzip -q dependency-check-7.2.0-release.zip
          rm dependency-check-7.2.0-release.zip

      - name: Run scan with ODC
        run: |
          dependency-check/bin/dependency-check.sh \
            --project "bitcoin" \
            --scan . \
            --format HTML \
            --format JSON \
            --failOnCVSS 7 \
            --suppression .github/owasp-suppressions.xml || true
        
      - name: Check for report files
        id: check-reports
        run: |
          if [ -f "dependency-check-report.html" ]; then
            echo "report_exists=true" >> $GITHUB_OUTPUT
          fi

      - name: Archive scan reports
        if: steps.check-reports.outputs.report_exists == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-reports
          path: |
            dependency-check-report.html
            dependency-check-report.json
          retention-days: 7