name: "owasp-scan"

on:
  push:
    branches: [githubcicd]

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 20  # Add timeout to prevent hanging jobs

    steps:
      - uses: actions/checkout@v3

      - name: Change script permission
        run: |
          chmod +x scripts/zap-script.sh

      - name: Cache ZAP
        id: cache-zap
        uses: actions/cache@v3
        with:
          path: ~/.ZAP
          key: zap-cache

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://your-application-url'  # Replace with your application URL
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

      - name: Check for report file
        id: check-report
        run: |
          if [ -f "zap-baseline-report.html" ]; then
            echo "report_exists=true" >> $GITHUB_OUTPUT
          fi

      - name: Archive ZAP Report
        if: steps.check-report.outputs.report_exists == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: zap-scan-report
          path: |
            zap-baseline-report.html
          retention-days: 7s